language: php

php: [5.4, 5.5]

env:
    - COVERALLS_REPO_TOKEN=0C0teLiqbzLFctzoa2jk6fgGLy8s1sTWb COVERALLS_RUN_LOCALLY=0

branches:
    only:
        - master

before_script:
    - env
    - git checkout master
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer self-update
    - composer install --dev --prefer-source --no-interaction --no-progress
    - npm install -g bower
    - bower update
    - php -S 127.0.0.1:8888 -t web/ &
    - sleep 4

script:
    - bin/behat --config app/config/behat.yml --profile php-server @RfBlogBundle
    - bin/phpspec run
    - bin/coveralls --config app/config/coveralls.yml -vvv